# Generated by Django 2.0.6 on 2018-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
