# Generated by Django 2.0.5 on 2018-06-26 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YYYY', models.IntegerField()),
                ('MM', models.IntegerField()),
                ('DD', models.IntegerField()),
                ('date_ended', models.DateTimeField()),
                ('text', models.TextField()),
                ('tag', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
